CREATE TRIGGER emainEnc
ON USERS
AFTER INSERT, UPDATE
AS
IF ( UPDATE (EMAIL) )
BEGIN
UPDATE USERS
SET EMAIL = AES_ENCRYPT(EMAIL, USER_ID)
WHERE USER_ID IN (SELECT DISTINCT USER_ID FROM inserted)
END;
