CREATE PROCEDURE [dbo].[TemplateFill]
    @GEAR_SCORE int,
    @CHAR_NAME varchar(25),
    @SERVER_NAME varchar(30),
    @A_HEAD varchar(6),
    @A_CHEST varchar(6),
    @A_HAND varchar(6),
    @A_LEGS varchar(6),
    @A_FEET varchar(6),
    @SHIELD varchar(5),
    @WEAPON1 varchar(15),
    @WEAPON2 varchar(15),
    @WEIGHT varchar(6)

AS
BEGIN

    INSERT INTO GEAR_SCORE(GEAR_SCORE) VALUES (@GEAR_SCORE)
    INSERT INTO CHAR_NAME(CHAR_NAME) VALUES (@CHAR_NAME)
    INSERT INTO SERVER_NAME(SERVER_NAME) VALUES (@SERVER_NAME)
    INSERT INTO A_HEAD(A_HEAD) VALUES (@A_HEAD)
    INSERT INTO A_CHEST(A_CHEST) VALUES (@A_CHEST)
    INSERT INTO A_HAND(A_HAND) VALUES (@A_HAND)
    INSERT INTO A_LEGS(A_LEGS) VALUES (@A_LEGS)
    INSERT INTO A_FEET(A_FEET) VALUES (@A_FEET)
    INSERT INTO SHIELD(SHIELD) VALUES (@SHIELD)
    INSERT INTO WEAPON1(WEAPON1) VALUES (@WEAPON1)
    INSERT INTO WEAPON2(WEAPON2) VALUES (@WEAPON2)
    INSERT INTO WEIGHT(WEIGHT) VALUES (@WEIGHT)

END

