CREATE PROC UserAddOrEdit
@USER_ID int,
@USERNAME varchar(25),
@PASSWORD varchar(45),
@EMAIL varchar(100)
AS
	IF @USER_ID = 0
	BEGIN
		INSERT INTO USERS (USERNAME, PASSWORD, EMAIL)
		VALUES (@USERNAME,@PASSWORD,@EMAIL)
		END
		ELSE
		BEGIN
		UPDATE USERS
		SET
		USERNAME = @USERNAME,
		PASSWORD = @PASSWORD,
		EMAIL = @EMAIL
		WHERE USER_ID = @USER_ID
		END